const { chromium } = require(process.argv[2]);
const R = []; const ok = (n, c, d = '') => R.push([c ? 'PASSOU' : 'FALHOU', n, d]);
(async () => { const b = await chromium.launch(); const ctx = await b.newContext(); const p = await ctx.newPage();
  const errs = []; p.on('pageerror', e => errs.push(e.message));
  await ctx.route('**/js/config.js', r => r.fulfill({ contentType: 'text/javascript', body: "window.MQ=window.MQ||{};MQ.CONFIG={supabaseUrl:'',supabaseAnonKey:'',semServiceWorker:true};" }));
  await ctx.route('**/cdn.jsdelivr.net/**', r => r.abort()); await ctx.route('**/fonts.g*/**', r => r.abort());
  await p.goto('http://localhost:8766/'); await p.evaluate(() => localStorage.clear()); await p.reload(); await p.waitForSelector('main');
  await p.evaluate(async () => { await navigator.serviceWorker.register('sw.js'); await navigator.serviceWorker.ready; });
  await p.reload(); await p.waitForSelector('main');
  ok('service worker controla a página', await p.evaluate(() => !!navigator.serviceWorker.controller));
  const guardados = await p.evaluate(async () => { const k = await caches.keys(); const c = await caches.open(k[0]); const ks = (await c.keys()).map(r => new URL(r.url).pathname); return [k[0], ks.length, ks.some(u => /js\/tudo\.js$/.test(u)) && ks.some(u => /css\/app\.css$/.test(u))]; });
  ok('pacote da versão guardado (' + guardados[0] + '): sistema num arquivo só + estilo', guardados[2] && guardados[1] >= 8, String(guardados[1]));
  await ctx.setOffline(true);
  const t0 = Date.now(); await p.reload(); await p.waitForSelector('main', { timeout: 15000 });
  ok('sem internet: abre o sistema do aparelho', true, (Date.now() - t0) + ' ms');
  await ctx.setOffline(false); await p.reload(); await p.waitForSelector('main');
  ok('com internet de volta: abre normal', true);
  ok('sem erro de página', errs.length === 0, errs.join('|'));
  await b.close(); R.forEach(r => console.log(r.join(' | '))); console.log('TOTAL', R.length, 'FALHAS', R.filter(r => r[0] === 'FALHOU').length);
})().catch(e => { console.error(e); process.exit(1); });
