const { chromium } = require(process.argv[2]);
const R = []; const ok = (n, c, d = '') => R.push([c ? 'PASSOU' : 'FALHOU', n, d]);
(async () => { const b = await chromium.launch(); const ctx = await b.newContext({ viewport: { width: 1280, height: 900 }, acceptDownloads: true }); const p = await ctx.newPage(); const errs = []; p.on('pageerror', e => errs.push(e.message));
  await ctx.route('**/js/config.js', r => r.fulfill({ contentType: 'text/javascript', body: "window.MQ=window.MQ||{};MQ.CONFIG={supabaseUrl:'',supabaseAnonKey:'',semServiceWorker:true};" }));
  await ctx.route('**/cdn.jsdelivr.net/**', r => r.abort()); await ctx.route('**/fonts.g*/**', r => r.abort());
  await p.goto('http://localhost:8766/'); await p.evaluate(() => localStorage.clear()); await p.reload(); await p.waitForSelector('.resumo');
  await p.click('button[data-p=coord_tecnico]'); await p.waitForTimeout(500); await p.evaluate(() => MQ.ui.fecharPainel());
  ok('Coordenação técnica não tem a aba Documentos', !(await p.$('[data-aba=documentos]')));
  await p.click('button[data-p=coord_geral]'); await p.waitForTimeout(500); await p.evaluate(() => MQ.ui.fecharPainel());
  ok('Coordenação geral tem a aba Documentos', !!(await p.$('nav.abas [data-aba=documentos]')));
  await p.click('nav.abas [data-aba=documentos]'); await p.waitForTimeout(300);
  await p.click('[data-acao=doc-novo]'); await p.waitForTimeout(300);
  await p.click('form[data-form=doc-enviar] button[type=submit]'); await p.waitForTimeout(200);
  ok('Anexar vazio: pede tipo, título e arquivo', (await p.$$eval('form[data-form=doc-enviar] .tem-erro', l => l.length)) >= 3);
  await p.selectOption('#dc-tipo', 'ata'); await p.fill('#dc-tit', 'Ata da reunião com o MPA'); await p.selectOption('#dc-uf', 'PI');
  await p.setInputFiles('#dc-arq', { name: 'ata.exe', mimeType: 'application/octet-stream', buffer: Buffer.from('x') });
  await p.click('form[data-form=doc-enviar] button[type=submit]'); await p.waitForTimeout(200);
  ok('Arquivo .exe recusado', /não aceito/.test(await p.textContent('form[data-form=doc-enviar]')));
  await p.setInputFiles('#dc-arq', { name: 'ata.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 teste') });
  await p.click('form[data-form=doc-enviar] button[type=submit]'); await p.waitForTimeout(500);
  ok('Documento anexado aparece na lista', /Ata da reunião com o MPA/.test(await p.textContent('#lista-docs').catch(() => '')));
  await p.click('#lista-docs [data-acao=doc-ver]'); await p.waitForTimeout(300);
  ok('Ficha do documento mostra arquivo e quem anexou', /ata\.pdf/.test(await p.textContent('.painel-corpo')) && /Cleone/.test(await p.textContent('.painel-corpo')));
  await p.click('form[data-form=doc-arquivar] button[type=submit]'); await p.waitForTimeout(200);
  ok('Arquivar sem motivo não arquiva', /motivo/i.test(await p.textContent('form[data-form=doc-arquivar]')));
  await p.fill('#da-mot', 'Versão sem assinatura'); await p.click('form[data-form=doc-arquivar] button[type=submit]'); await p.waitForTimeout(400);
  ok('Arquivado sai da lista e vai para Arquivados', !(await p.$('#lista-docs')) && /Arquivados \(1\)/.test(await p.textContent('main')));
  await p.click('[data-acao=doc-relatorio]'); await p.waitForTimeout(400);
  const rel = await p.textContent('.rel');
  ok('Relatório tem as 7 partes', ['1. Equipe', '2. Seleção', '3. Trabalho de campo', '4. Curso FIC', '5. Pagamentos', '6. Viagens', '7. Documentos'].every(x => rel.includes(x)), rel.slice(0, 120));
  const nomesMulheres = await p.evaluate(() => (MQ.ui.S.fichas || []).map(f => f.nome));
  ok('Relatório sem nome de mulher', !nomesMulheres.some(n => rel.includes(n)));
  await p.fill('#rl-de', '2026-12-01'); await p.fill('#rl-ate', '2026-10-01'); await p.click('form[data-form=doc-rel-filtro] button[type=submit]'); await p.waitForTimeout(200);
  ok('Período com fim antes do início é recusado', /antes do início/.test(await p.textContent('form[data-form=doc-rel-filtro]')));
  await p.fill('#rl-de', '2026-09-14'); await p.fill('#rl-ate', await p.evaluate(() => MQ.regras.hoje())); await p.selectOption('#rl-uf', 'BA'); await p.click('form[data-form=doc-rel-filtro] button[type=submit]'); await p.waitForTimeout(300);
  ok('Filtro por estado', /Estados: Bahia/.test(await p.textContent('.rel')));
  const [dl] = await Promise.all([p.waitForEvent('download'), p.click('[data-acao=doc-rel-word]')]);
  const conteudo = require('fs').readFileSync(await dl.path(), 'utf8');
  ok('Baixar para o Word gera .doc com o relatório', /\.doc$/.test(dl.suggestedFilename()) && /Relatório da ação do projeto/.test(conteudo), dl.suggestedFilename());
  await p.evaluate(() => MQ.ui.fecharPainel()); await p.click('nav.abas [data-aba=historico]'); await p.waitForTimeout(300);
  ok('Histórico registra anexar e arquivar', /anexou o documento/.test(await p.textContent('main')) && /arquivou o documento/.test(await p.textContent('main')));
  await p.setViewportSize({ width: 390, height: 844 }); await p.evaluate(() => { MQ.ui.S.aba = 'documentos'; MQ.ui.render(); }); await p.waitForTimeout(300);
  ok('Celular: sem rolagem lateral', (await p.evaluate(() => document.documentElement.scrollWidth)) <= 390);
  await p.screenshot({ path: '/tmp/claude-0/pw/cad/docs390.png' });
  ok('Sem erro de JavaScript', !errs.length, errs.join(' | '));
  R.forEach((r, i) => console.log(String(i + 1).padStart(2), r[0], '|', r[1], r[0] === 'FALHOU' ? '| ' + r[2] : ''));
  console.log('TOTAL', R.filter(r => r[0] === 'PASSOU').length, 'passou,', R.filter(r => r[0] === 'FALHOU').length, 'falhou');
  await b.close(); })().catch(e => { console.log('ERRO', e.message.slice(0, 400)); R.forEach(r => console.log(r.join(' | '))); });
